version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn install
      - mv target/pylon-service-*.jar pylon-service.jar
artifacts:
  files:
    - pylon-service.jar
    - .ebextensions/**/*
