version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn install
      - mv target/pylon-service-*.war ROOT.war
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*
