package com.pylon.pylonservice.model.tables;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Setter;

import java.util.Date;

@AllArgsConstructor
@Builder
@NoArgsConstructor
@Setter
@DynamoDBTable(tableName = "-Notification")
public class Notification {
    private static final String USER_NOTIFICATION_GSI_NAME = "UserNotification";

    String notificationId;
    @NonNull
    String toUsername;
    @NonNull
    Date createdAt;
    @NonNull
    String fromUsername;
    @NonNull
    boolean isRead;
    @NonNull
    int notificationType;
    String postId;
    String commentPostId;
    String includedShardName;
    String includingShardName;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getNotificationId() {
        return notificationId;
    }

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = USER_NOTIFICATION_GSI_NAME)
    public String getToUsername() {
        return toUsername;
    }

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = USER_NOTIFICATION_GSI_NAME)
    public Date getCreatedAt() {
        return createdAt;
    }

    @DynamoDBAttribute
    public String getFromUsername() {
        return fromUsername;
    }

    @DynamoDBAttribute
    public boolean isRead() {
        return isRead;
    }

    @DynamoDBAttribute
    public int getNotificationType() {
        return notificationType;
    }

    @DynamoDBAttribute
    public String getPostId() {
        return postId;
    }

    @DynamoDBAttribute
    public String getCommentPostId() {
        return commentPostId;
    }

    @DynamoDBAttribute
    public String getIncludedShardName() {
        return includedShardName;
    }

    @DynamoDBAttribute
    public String getIncludingShardName() {
        return includingShardName;
    }
}
